doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
          enum_diff_algorithm: DR\GitCommitNotification\Doctrine\Type\DiffAlgorithmType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
          DR\GitCommitNotification:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'DR\GitCommitNotification\Entity'
                alias: DR\GitCommitNotification

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
