liip_monitor:
  enable_controller: true
  checks:
    groups:
      default:
        php_extensions: [ amqp, intl, iconv, pdo_mysql, json ]
        opcache_memory:
          warning: 70
          critical: 90

        # Checks to see if the APC memory usage is below warning/critical thresholds
        apc_memory:
          warning: 70
          critical: 90

        # Checks to see if the APC fragmentation is below warning/critical thresholds
        apc_fragmentation:
          warning: 70
          critical: 90

        # Connection name or an array of connection names
        #doctrine_dbal: 'default'

        messenger_transports:
          async_messages:
            critical_threshold: 10

          async_revisions:
            critical_threshold: 50

          async_delay_mail:
            critical_threshold: 50
