## overrides for production

version: '3'

services:
    nginx:
        volumes:
            - ./docker/ssl/production/dhparam.pem:/etc/ssl/certs/dhparam.pem:ro
            - ./docker/ssl/production/production.crt:/etc/ssl/certs/123view-cert.crt:ro
            - ./docker/ssl/production/production.key:/etc/ssl/private/123view-cert.key:ro
        restart: unless-stopped

    php-fpm:
        build:
            target: prod
        environment:
            DATABASE_URL: mysql://${DB_USER}:${DB_PASS}@mysql:3306/${DB_NAME:-123view}?serverVersion=${MYSQL_VERSION}&charset=utf8mb4
            APP_ENV: prod
        restart: unless-stopped

    mysql:
        environment:
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
            MYSQL_DATABASE: ${DB_NAME:-123view}
            MYSQL_ROOT_PASSWORD: ${DB_PASS}
        restart: unless-stopped

    rabbitmq:
        environment:
            RABBITMQ_DISK_FREE_ABSOLUTE_LIMIT: 1GB
        restart: unless-stopped

    mercure:
        volumes:
            - ./docker/ssl/production/production.crt:/etc/ssl/certs/123view-cert.crt:ro
            - ./docker/ssl/production/production.key:/etc/ssl/private/123view-cert.key:ro
        restart: unless-stopped

    mail:
        restart: unless-stopped
