[supervisord]
nodaemon=true
user=root
logfile=/tmp/supervisord.log
pidfile=/var/run/supervisord.pid

[program:highlightjs-server]
command=node /app/docker/nodejs/run/highlight.js
priority=1
directory=/app
autostart=true
autorestart=true
startsecs=10
startretries=3
stopwaitsecs=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:anthropic-server]
command=node /app/docker/nodejs/run/anthropic.js
priority=1
directory=/app
autostart=true
autorestart=true
startsecs=10
startretries=3
stopwaitsecs=20
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
