name: Test

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        name: PHP ${{ matrix.php-versions }} Test
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: [ '8.1' ]
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    coverage: none
            -   name: Validate composer.json and composer.lock
                run: composer validate
            -   name: Install dependencies
                run: composer update --prefer-dist --no-progress --no-suggest --prefer-stable
            -   name: Run test suite
                run: composer test
    coverage:
        name: PHP coverage
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    coverage: pcov
            -   name: Install dependencies
                run: composer update --prefer-dist --no-progress --no-suggest --prefer-stable
            -   name: Run test suite
                run: php -dmax_execution_time=300 -dpcov.enabled=1 -dpcov.exclude="~vendor~" vendor/bin/phpunit --testsuite unit --coverage-clover ./.coverage/coverage.xml
            -   name: Check coverage
                run: test ! -f ./.coverage/coverage.xml || php vendor/bin/phpfci inspect ./.coverage/coverage.xml ./.coverage/phpfci.xml --exit-code-on-failure
